### PR TITLE
Fix update user

### PR DESCRIPTION
**Pull request by sara-rioseco**
Fix update user info.
- any user can update their own password using PATCH through the update password endpoint ('http://localhost:3000/me/:id'). The body must be in json and have a "password" and a "newPassword" attributes.
- any admin user can update their info (except password, email and rut) using PATCH method through the update endpoint ('http://localhost:3000/:id').
- any regular user can update only their name, surname and country using PATCH method through the update endpoint ('http://localhost:3000/:id').

### CODE REVIEW

**Comment by spancavil** [comment]
Hi girls! Could you upload please the entire Postman collection? In JSON format. If you want add it to documentation or as a new file.  Thanks!

**Comment by spancavil** [comment]
Nevermind it's already in the documentation, and are few endpoints. I will check it.

**Comment by spancavil** [comment]
any user can update their own password using PATCH through the update password endpoint ('http://localhost:3000/me/:id'). The body must be in json and have a "password" and a "newPassword" attributes => OK

any admin user can update their info (except password, email and rut) using PATCH method through the update endpoint ('http://localhost:3000/:id') => OK

any regular user can update only their name, surname and country using PATCH method through the update endpoint ('http://localhost:3000/:id') => Regular user forbidden. See screen below:
image

**Comment by sara-rioseco** [comment]
That's weird. I proved it just now and it's working for me. 
Did you make sure the id param is for the same user as the token?

image

**Comment by spancavil** [comment]
Yeah it's ok. I was positioned at "main" lol. In this branch works perfectly!

**Review by spancavil — APPROVED** [review]

**Pull request merged**
